### ISSUE TITLE
Unable to parse translation unit if precompiled headers are enabled

### ISSUE THREAD

**Issue by hmoffatt** [bkryza/clang-include-graph#1]
I'm using clang 14, and I normally have precompiled headers enabled. However, clang-include-graph is failing with

```
$ ~/src/clang-include-graph/release/clang-include-graph -v
=== Loading compilation database from /home/hamish/src/include-test
=== Parsing translation unit: /home/hamish/src/include-test/precompiled.h
=== Parsing translation unit: /home/hamish/src/include-test/main.cc
ERROR: Unable to parse translation unit - aborting...
```

My precompiled header just includes a bunch of STL and Qt headers. If I turn off precompiled headers then it works fine.

Here's my test project.
[include-test.tar.gz](https://github.com/bkryza/clang-include-graph/files/11900901/include-test.tar.gz)

**Comment by bkryza** [comment]
@hmoffatt Thanks for the issue - I've never tried this with precompiled headers enabled - I'll look into it...

**Comment by hmoffatt** [comment]
Thanks for this tool!

**Comment by bkryza** [comment]
@hmoffatt I've checked your test project and it works fine - I had to adjust slightly the paths because I've installed qt differently, but after that it works fine:

```
❯ cat compile_commands.json
[
  {
    "arguments": [
      "/usr/bin/clang++",
      "-c",
      "-pipe",
      "-O2",
      "-std=gnu++2a",
      "-Wall",
      "-Wextra",
      "-fPIC",
      "-D_REENTRANT",
      "-DQT_NO_DEBUG",
      "-DQT_GUI_LIB",
      "-DQT_CORE_LIB",
      "-I.",
      "-I../dev/Qt-6.5.1/include",
      "-I../dev/Qt-6.5.1/include/QtGui",
      "-I../dev/Qt-6.5.1/include/QtCore",
      "-I.",
      "-I../dev/Qt6.5.1/6.5.1/gcc_64/mkspecs/linux-clang",
      "-o",
      "main.o",
      "main.cc"
    ],
    "directory": "/home/bartek/devel/clang-include-graph-issues/1/include-test",
    "file": "/home/bartek/devel/clang-include-graph-issues/1/include-test/main.cc",
    "output": "/home/bartek/devel/clang-include-graph-issues/1/include-test/main.o"
  }
]
```


```shell
❯ ../../../clang-include-graph/cmake-build-debug/clang-include-graph -s | grep Qt | head
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qconfig.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtcore-config.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtversionchecks.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtconfigmacros.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtcoreexports.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtpreprocessorsupport.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtnoop.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qsystemdetection.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qprocessordetection.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qcompilerdetection.h
```

In the `main` branch I've just added a commit, which generates a warning on stderr, when an include file is not found. If it generates a warning on your system, it means that libclang cannot find the header included in the reported line based on the include paths found in `compile_commands.json` and you need to adjust them properly.

If it still crashes, but you don't get this warning please let me know.

**Comment by hmoffatt** [comment]
I don't get any extra output;

```
=== Loading compilation database from /home/hamish/src/include-test
=== Parsing translation unit: /home/hamish/src/include-test/precompiled.h
=== Parsing translation unit: /home/hamish/src/include-test/main.cc
ERROR: Unable to parse translation unit - aborting...
```

I think I might have attached the example project with the precompiled headers disabled; here's one that definitely isn't working.

```
  {
    "arguments": [
      "/usr/bin/clang++",
      "-pipe",
      "-O2",
      "-std=gnu++2a",
      "-Wall",
      "-Wextra",
      "-fPIC",
      "-D_REENTRANT",
      "-DQT_NO_DEBUG",
      "-DQT_GUI_LIB",
      "-DQT_CORE_LIB",
      "-I.",
      "-I../../dev/Qt6.5.1/6.5.1/gcc_64/include",
      "-I../../dev/Qt6.5.1/6.5.1/gcc_64/include/QtGui",
      "-I../../dev/Qt6.5.1/6.5.1/gcc_64/include/QtCore",
      "-I.",
      "-I../../dev/Qt6.5.1/6.5.1/gcc_64/mkspecs/linux-clang",
      "-x",
      "c++-header",
      "-c",
      "-o",
      "test.pch/c++.pch",
      "precompiled.h"
    ],
    "directory": "/home/hamish/src/include-test",
    "file": "/home/hamish/src/include-test/precompiled.h",
    "output": "/home/hamish/src/include-test/test.pch/c++.pch"
  },


```

[include-test.tar.gz](https://github.com/bkryza/clang-include-graph/files/11911189/include-test.tar.gz)

**Comment by bkryza** [comment]
@hmoffatt Ok, thanks, now I see the problem. Could you give me instructions on how you compile this and how you created `compile_commands.json` - I've tried on my system but instead of `test.pch` I get a `test.gch` - no idea if it's the same:

```
❯ ../dev/Qt-6.5.1/bin/qmake  test.pro
❯ make
g++ -pipe -O2 -std=gnu++2a -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../dev/Qt-6.5.1/include -I../dev/Qt-6.5.1/include/QtGui -I../dev/Qt-6.5.1/include/QtCore -I. -I../dev/Qt-6.5.1/mkspecs/linux-g++ -x c++-header -c precompiled.h -o test.gch/c++
g++ -c -include test -pipe -O2 -std=gnu++2a -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../dev/Qt-6.5.1/include -I../dev/Qt-6.5.1/include/QtGui -I../dev/Qt-6.5.1/include/QtCore -I. -I../dev/Qt-6.5.1/mkspecs/linux-g++ -o main.o main.cc
```

**Comment by hmoffatt** [comment]
I use `qmake -spec linux-clang` to target clang, and `bear` to build the commands database.

**Comment by hmoffatt** [comment]
I have no reason to think this is anything to do with Qt, but it just happens that I'm using qmake and it knows how to tell the compiler how to use precompiled headers and I don't. Sorry for the extra bother.

**Comment by bkryza** [comment]
You're it has nothing to do with Qt or qmake, it's only related to PCH. First of I can skip the precompiled header generation command from compile_commands.json, the second thing is that on the compile command for `main.cc`, parsing the translation unit fails when I leave the arguments `-Xclang -include-pch -Xclang test.pch/c++.pch`. If I remove them from the compile command arguments it works (but obviously it traverses the include tree using the original include files - not the precompiled header file).

The question is is whether this is ok, i.e. will clang have access to the original include files when you run it and I can just skip the PCH header altogether during loading of `compile_commands.json`?

**Comment by bkryza** [comment]
@hmoffatt I've created a branch `fix-handling-of-pch-files`, in which it seems to work - basically I'm ignoring the PCH compile commands and arguments and processing the headers as if there was no PCH, it seems to work:

```
❯ ../dev/Qt-6.5.1/bin/qmake -spec linux-clang test.pro
❯ bear -- make
clang++ -pipe -O2 -std=gnu++2a -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../dev/Qt-6.5.1/include -I../dev/Qt-6.5.1/include/QtGui -I../dev/Qt-6.5.1/include/QtCore -I. -I../dev/Qt-6.5.1/mkspecs/linux-clang -x c++-header -c precompiled.h -o test.pch/c++.pch
clang++ -c -Xclang -include-pch -Xclang test.pch/c++.pch -pipe -O2 -std=gnu++2a -Wall -Wextra -fPIC -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../dev/Qt-6.5.1/include -I../dev/Qt-6.5.1/include/QtGui -I../dev/Qt-6.5.1/include/QtCore -I. -I../dev/Qt-6.5.1/mkspecs/linux-clang -o main.o main.cc
clang++ -ccc-gcc-name g++ -Wl,-rpath,/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/lib -Wl,-rpath-link,/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/lib -o test  main.o   /home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/lib/libQt6Gui.so /home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
❯ ../../../clang-include-graph/cmake-build-debug/clang-include-graph -s | grep Qt | head
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qconfig.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtcore-config.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtversionchecks.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtconfigmacros.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtcoreexports.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtpreprocessorsupport.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qtnoop.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qsystemdetection.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qprocessordetection.h
/home/bartek/devel/clang-include-graph-issues/1/dev/Qt-6.5.1/include/QtCore/qcompilerdetection.h
```

If possible, can you check if this now works for you?

**Comment by hmoffatt** [comment]
> If possible, can you check if this now works for you?

It does. Thanks!

> The question is is whether this is ok, i.e. will clang have access to the original include files when you run it and I can just skip the PCH header altogether during loading of `compile_commands.json`?

I think that's fine. PCH is only a tool for speeding up the compile, original files should still be accessible.

**Comment by hmoffatt** [comment]
On an unrelated note, I had to remove -Werror from the compile flags else I got warnings from the boost headers. I used boost 1.74 as that's what I have on Debian 12. I don't know if this is a boost issue or a clang-include-graph issue. I can open a separate issue if you want to loo into it.

**Comment by bkryza** [comment]
Yes, please create a new issue - it could probably be fixed by adding an option to specify a query driver to the compile commands which extracts flags and include paths from the specified compiler driver (e.g. you can explicity say to ask /usr/bin/clang++-14 for it's system include paths and flags), this is for instance used by `clangd` server...
